{% set name = "nsls2-detector-handlers" %}
{% set version = "0.0.3" %}
{% set sha256 = "cba05310d9192212cab61300b08f7dbfb0181756e4c5292d0c2f266a72cbf37e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py
    - numpy
    - pandas

test:
  imports:
    - nsls2_detector_handlers

about:
  home: https://github.com/bluesky/nsls2-detector-handlers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Detector handlers specific to NSLS-II

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
